# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DALI Build
tagline: resources, workshops, etc
email: staff@dali.dartmouth.edu
# About/contact
author:
  name:       DALI Lab
  url:        "http://build.dali.dartmouth.edu"
description: > # this means to ignore newlines until "baseurl:"
  resources, workshops, etc
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://build.dali.dartmouth.edu" # the base hostname & protocol for your site
twitter_username: dali_lab
github_username: dali-lab

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true

gems:
  - jemoji
